//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfastResource.Resource.Exercise20.UsingResources.zdania.na_tym_dywanie_jest_mnostwo_smieci {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AfastResource.Resource.Exercise20.UsingResources.zdania.na_tym_dywanie_jest_mnost" +
                            "wo_smieci.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAPTOP.
        /// </summary>
        internal static string answer_one {
            get {
                return ResourceManager.GetString("answer_one", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ŁYŻKA.
        /// </summary>
        internal static string answer_two {
            get {
                return ResourceManager.GetString("answer_two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ODKURZACZ.
        /// </summary>
        internal static string correctAnswer {
            get {
                return ResourceManager.GetString("correctAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NA TYM DYWANIE JEST MNÓSTWO ŚMIECI..
        /// </summary>
        internal static string sentence {
            get {
                return ResourceManager.GetString("sentence", resourceCulture);
            }
        }
    }
}
