//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AfastResource.Resource.Exercise30.LearningResources.Zrobiło_się_późno {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AfastResource.Resource.Exercise30.LearningResources.Zrobiło_się_późno.texts", typeof(texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrobiło się późno,.
        /// </summary>
        internal static string complexOne {
            get {
                return ResourceManager.GetString("complexOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pójdę już do domu..
        /// </summary>
        internal static string complexTwo {
            get {
                return ResourceManager.GetString("complexTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to więc.
        /// </summary>
        internal static string conjunction {
            get {
                return ResourceManager.GetString("conjunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrobiło się późno..
        /// </summary>
        internal static string simpleOne {
            get {
                return ResourceManager.GetString("simpleOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pójdę już do domu..
        /// </summary>
        internal static string simpleTwo {
            get {
                return ResourceManager.GetString("simpleTwo", resourceCulture);
            }
        }
    }
}
